server:
  port: 8080

spring:
  application:
    name: order-service
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8081}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
