server:
  port: 8080

spring:
  application:
    name: locking-demo
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

redisson:
  single-server-config:
    address: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
